package com.featureflagx.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.time.Instant;

@Entity
@Table(name = "flags")
@Getter
@Setter
public class Flag {

    @Id
    @Column(name = "key")
    private String key;

    @Column(nullable = false)
    private boolean enabled;

    @Column(columnDefinition = "jsonb") // Or TEXT if jsonb is not directly supported by H2 for tests without extra config
    private String config; // Store JSON as String

    @Column(name = "updated_at")
    private Instant updatedAt;

    // Lombok will generate getters and setters
    // Constructors, equals, hashCode, toString can be added if needed or also generated by Lombok
}

