package com.featureflagx.dto;

import lombok.Getter;
import lombok.Setter;

// Using Lombok for boilerplate code reduction (getters, setters)
@Getter
@Setter
public class FlagRequest {
    private String key;
    private boolean enabled;
    private String config; // JSON string for configuration

    // Constructors, if needed, can be added or generated by Lombok (@NoArgsConstructor, @AllArgsConstructor)
}

